"""Assemble src/hook.s and refresh onescreen/payload/.

Run this after editing the hook. It regenerates both the binary blob and the
symbol metadata, so the addresses can never drift out of sync with the code
(hand-writing them once produced a load address 0xA00 bytes off, which silently
put the payload in the wrong place).

Requires devkitARM.  https://devkitpro.org/
"""

import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEVKIT = pathlib.Path(r"C:\devkitPro\devkitARM\bin")
AS, LD, OBJCOPY, NM = (DEVKIT / f"arm-none-eabi-{t}" for t in ("as", "ld", "objcopy", "nm"))

ITCM_BASE = 0x01FF8000
ITCM_END = 0x02000000
ITCM_USED = 0x620
LOAD_ADDR = ITCM_BASE + ITCM_USED


def main(auto_battle=True):
    work = ROOT / "build"
    work.mkdir(exist_ok=True)
    src = ROOT / "src" / "hook.s"
    obj, elf, binf = work / "hook.o", work / "hook.elf", work / "hook.bin"

    cmd = [str(AS), "-mcpu=arm946e-s", "-mthumb"]
    if not auto_battle:
        cmd += ["--defsym", "DISABLE_AUTO_BATTLE=1"]
    subprocess.run(cmd + ["-o", str(obj), str(src)], check=True)
    subprocess.run([str(LD), f"-Ttext=0x{LOAD_ADDR:08X}", "-o", str(elf), str(obj)],
                   check=True)
    subprocess.run([str(OBJCOPY), "-O", "binary", str(elf), str(binf)], check=True)

    out = subprocess.run([str(NM), str(elf)], capture_output=True, text=True,
                         check=True).stdout
    symbols = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2].startswith("OneScreen_"):
            symbols[parts[2]] = f"0x{int(parts[0], 16):08X}"

    payload = binf.read_bytes()

    # Read the version out of the assembled blob rather than repeating it here.
    # It lives in OneScreen_Signature: "1SGS" followed by the version word.
    sig = symbols.get("OneScreen_Signature")
    if sig is None:
        raise SystemExit("OneScreen_Signature is missing from the payload")
    off = int(sig, 16) - LOAD_ADDR
    if payload[off:off + 4] != b"1SGS":
        raise SystemExit(f"signature not found at {sig} (got {payload[off:off + 4]!r})")
    version = int.from_bytes(payload[off + 4:off + 8], "little")

    dest = ROOT / "onescreen" / "payload"
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "hook.bin").write_bytes(payload)
    metadata = json.dumps({
        "comment": "Generated by tools/make_payload.py - do not edit by hand.",
        "payload_version": version,
        "load_addr": f"0x{LOAD_ADDR:08X}",
        "size": len(payload),
        "symbols": dict(sorted(symbols.items(), key=lambda kv: kv[1])),
    }, indent=2) + "\n"
    # Keep the generated file byte-stable on Windows too. Path.write_text uses
    # platform newline translation, which made every line look like trailing
    # whitespace to `git diff --check` in this repository.
    (dest / "hook.json").write_bytes(metadata.encode("utf-8"))

    print(f"payload: {len(payload)} bytes at {LOAD_ADDR:#010x} "
          f"({ITCM_END - LOAD_ADDR - len(payload)} bytes of ITCM left)")
    for name, addr in sorted(symbols.items(), key=lambda kv: kv[1]):
        print(f"  {addr}  {name}")


if __name__ == "__main__":
    main()
